name=VirgilJSP
version=1.0.0
author=Vergus
maintainer=Vergus
sentence=JSON Sensor Protocol for Vergus Virgil water monitor
paragraph=Simple library to integrate any ESP32/ESP8266 sensor with Vergus Virgil intelligent water monitoring system via the open JSP protocol. Supports alarm events, battery monitoring, deep sleep optimization and automatic heartbeat.
category=Communication
url=https://github.com/Vergus/VirgilJSP
architectures=esp32,esp8266
depends=ArduinoJson
keywords=water-leak,flood,sensor,ESP32,ESP8266,IoT,smart-home,home-automation,JSON,HTTP,webhook,water-monitor,domotica,Zigbee,MQTT,Home-Assistant
